// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDQFkVcRyPdgOQbaNhTBMoymywn9ZzLj4',
    appId: '1:623290237634:web:deb78bba51fb2c3238f15b',
    messagingSenderId: '623290237634',
    projectId: 'tdahfirst-mhvs',
    authDomain: 'tdahfirst-mhvs.firebaseapp.com',
    storageBucket: 'tdahfirst-mhvs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7LJR1cPW9YT_eB2DMdl4wMTkCh2jO2Os',
    appId: '1:623290237634:android:213cc2749a46d68338f15b',
    messagingSenderId: '623290237634',
    projectId: 'tdahfirst-mhvs',
    storageBucket: 'tdahfirst-mhvs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyCbc6RWTfYTootoD2fl6HVtvd9_blGGI',
    appId: '1:623290237634:ios:1ac8c69cc0fdc91138f15b',
    messagingSenderId: '623290237634',
    projectId: 'tdahfirst-mhvs',
    storageBucket: 'tdahfirst-mhvs.appspot.com',
    iosClientId: '623290237634-7j3eiaai2qgcmudccbgbh4i0kfq5nbe1.apps.googleusercontent.com',
    iosBundleId: 'com.example.auth',
  );
}
